### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by AndreyBaglai** [AndreyBaglai/homepage#4]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by mustang-eleanor** [comment]
**Sports career**

+ Oleksiy started weightlifting in 2000. In 2005 he joined the Ukrainian national Olympic weightlifting team.

+ In 2006, at the European Junior Championships, he became a bronze medalist in the snatch and clean & jerk.

+ In 2007 he became the winner of the World Weightlifting Cup in Apia.

+ In 2008, he became a participant of the XXIX Olympic Games in Beijing, where he became one of the 10 strongest athletes in the category of up to 105 kg. Due to a lack of financial support, he had to retire from competitive Olympic Weightlifting right after the Olympic Games 2008 in Beijing. 5 months after his retirement, he got a sponsor, that allowed him to continue with his professional career.

+ In 2009 he became a silver medalist in European Championships in Bucharest (405 kg).

+ In 2010, he received the silver in clean & jerk and became the bronze medalist of the European Weightlifting Championships in Minsk.

+ In 2011 in Paris, Oleksiy Torokhtiy became the bronze medalist of the World Championship.

+ On August 6, 2012 in London Oleksiy became the Olympic Gold Medalist in weightlifting in the category 105 kg.

+ On 22 December 2018, it was announced that as a consequence of the International Olympic Committee’s re-analysis program in connection with the 2012 London Olympic Games Oleksiy had tested positive for performance-enhancing drugs. and in December 2019 it was confirmed that he had been disqualified.
